#!/usr/bin/env python
import sys; sys.path += ['/var/canvas/common', '../../common']

import datetime
import time
import os.path
import copy
import cStringIO
import gzip
import json

import ec2

td = datetime.timedelta

def main():

    import sys
    
    if len(sys.argv) != 2:
        print "Usage: fetch_access_logs [output_path]"
        return
    
    basepath = sys.argv[1]

    s3_conn = ec2.s3_connection()
    bucket = s3_conn.get_bucket('canvas-facts')

    for key in bucket.list(prefix='ugc_logs/'):
        filename = os.path.basename(key.name)
        key.get_contents_to_filename(os.path.join(basepath, filename))

if __name__ == "__main__":
    main()
