#!/usr/bin/env python
import sys; sys.path += ['/var/canvas/common', '../../common']

import ec2

def main(name, value):
    instance_id = ec2.get_instance_id()
    ec2.connection().create_tags([instance_id], {name: value})

if __name__ == "__main__":
    name, value = sys.argv[1:]
    main(name, value)
